import type { News, Style, Staff } from "@/lib/types";

const now = new Date().toISOString();

export const dummyNewsList: News[] = [
  {
    id: "news-1",
    createdAt: now,
    updatedAt: now,
    publishedAt: now,
    revisedAt: now,
    title: "年末年始の営業のお知らせ",
    content: "<p>年末年始の営業時間についてお知らせします。12月31日〜1月3日は休業いたします。</p>",
    category: "news",

    excerpt: "年末年始の営業時間についてお知らせします。",
  },
  {
    id: "news-2",
    createdAt: now,
    updatedAt: now,
    publishedAt: now,
    revisedAt: now,
    title: "新メニュー登場のお知らせ",
    content: "<p>新しいトリートメントメニューが登場しました。ぜひお試しください。</p>",
    category: "news",

    excerpt: "新しいトリートメントメニューが登場しました。",
  },
  {
    id: "news-3",
    createdAt: now,
    updatedAt: now,
    publishedAt: now,
    revisedAt: now,
    title: "臨時休業のお知らせ",
    content: "<p>諸事情により、3月10日（月）は臨時休業とさせていただきます。</p>",
    category: "news",

    excerpt: "3月10日（月）は臨時休業とさせていただきます。",
  },
  {
    id: "blog-1",
    createdAt: now,
    updatedAt: now,
    publishedAt: now,
    revisedAt: now,
    title: "春のヘアカラートレンド2026",
    content: "<p>今年の春トレンドカラーをご紹介します。透明感のある柔らかいカラーが人気です。</p>",
    category: "blog",

    excerpt: "今年の春トレンドカラーをご紹介します。",
    eyecatch: { url: "https://picsum.photos/seed/blog1/800/450", width: 800, height: 450 },
    tags: ["ヘアカラー", "トレンド"],
  },
  {
    id: "blog-2",
    createdAt: now,
    updatedAt: now,
    publishedAt: now,
    revisedAt: now,
    title: "ヘアケアの基本：正しいシャンプーの方法",
    content: "<p>毎日のシャンプーで気をつけたいポイントをお伝えします。</p>",
    category: "blog",

    excerpt: "毎日のシャンプーで気をつけたいポイントをお伝えします。",
    eyecatch: { url: "https://picsum.photos/seed/blog2/800/450", width: 800, height: 450 },
    tags: ["ヘアケア"],
  },
  {
    id: "blog-3",
    createdAt: now,
    updatedAt: now,
    publishedAt: now,
    revisedAt: now,
    title: "縮毛矯正とストレートパーマの違い",
    content: "<p>縮毛矯正とストレートパーマ、どちらを選べばいいか迷っている方へ解説します。</p>",
    category: "blog",

    excerpt: "縮毛矯正とストレートパーマの違いを解説します。",
    eyecatch: { url: "https://picsum.photos/seed/blog3/800/450", width: 800, height: 450 },
    tags: ["パーマ・縮毛矯正"],
  },
];

export const dummyStyleList: Style[] = [
  {
    id: "style-1",
    createdAt: now,
    updatedAt: now,
    publishedAt: now,
    revisedAt: now,
    title: "ナチュラルボブ",
    image: { url: "https://picsum.photos/seed/style1/600/800", width: 600, height: 800 },
    stylist: "橋本 貴広",
    menu: "カット",
    description: "自然な動きを活かしたナチュラルボブスタイル。",
  },
  {
    id: "style-2",
    createdAt: now,
    updatedAt: now,
    publishedAt: now,
    revisedAt: now,
    title: "ハイライトカラー",
    image: { url: "https://picsum.photos/seed/style2/600/800", width: 600, height: 800 },
    stylist: "橋本 貴広",
    menu: "オールハイライト + カット",
    description: "立体感と透明感を演出するハイライトカラー。",
  },
  {
    id: "style-3",
    createdAt: now,
    updatedAt: now,
    publishedAt: now,
    revisedAt: now,
    title: "外ハネミディアム",
    image: { url: "https://picsum.photos/seed/style3/600/800", width: 600, height: 800 },
    stylist: "橋本 貴広",
    menu: "カット + デザインパーマ",
    description: "トレンドの外ハネデザインパーマスタイル。",
  },
  {
    id: "style-4",
    createdAt: now,
    updatedAt: now,
    publishedAt: now,
    revisedAt: now,
    title: "艶やかストレート",
    image: { url: "https://picsum.photos/seed/style4/600/800", width: 600, height: 800 },
    stylist: "橋本 貴広",
    menu: "髪質改善縮毛矯正",
    description: "サラサラ・ツヤツヤの美しいストレートヘア。",
  },
  {
    id: "style-5",
    createdAt: now,
    updatedAt: now,
    publishedAt: now,
    revisedAt: now,
    title: "ウルフカット",
    image: { url: "https://picsum.photos/seed/style5/600/800", width: 600, height: 800 },
    stylist: "橋本 貴広",
    menu: "カット",
    description: "レイヤーを活かしたトレンドのウルフスタイル。",
  },
  {
    id: "style-6",
    createdAt: now,
    updatedAt: now,
    publishedAt: now,
    revisedAt: now,
    title: "グラデーションカラー",
    image: { url: "https://picsum.photos/seed/style6/600/800", width: 600, height: 800 },
    stylist: "橋本 貴広",
    menu: "ヘアカラーオール + カット",
    description: "根元から毛先に向かってグラデーションで仕上げたカラー。",
  },
];

export const dummyStaffList: Staff[] = [
  {
    id: "staff-1",
    createdAt: now,
    updatedAt: now,
    publishedAt: now,
    revisedAt: now,
    name: "橋本 貴広",
    nameEn: "Takahiro Hashimoto",
    position: "owner / hair designer",
    photo: { url: "https://imgbp.hotp.jp/CSP/IMG_SRC/72/38/B252057238/B252057238.jpg", width: 400, height: 400 },
    profile: "<p>横浜元町の美容院 teal. のオーナー兼ヘアデザイナー。お客様一人ひとりに寄り添ったスタイルをご提案します。</p>",
    message: "あなたの魅力を最大限に引き出すスタイルをご一緒に作りましょう。",
  },
];
